[package]
name = "safe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
color-eyre = "0.6.2"
dialoguer = { version = "0.10.4", features = ["fuzzy-select"] }
fastrand = "2.0.0"
fuzzy-matcher = "0.3.7"
itertools = "0.11.0"
rayon = {version = "1.7.0", optional = true }
ron = "0.8.1"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.105"
tabled = "0.14.0"
tiny_http = { version  = "0.12.0", optional = true }

[features]
web = ["tiny_http"]
paralell_queries = ["rayon"]
default = ["web"]
